### ISSUE TITLE
启用该集成后出现登录问题

### ISSUE THREAD

**Issue by kingandwood** [Yonsm/ZhiBot#3]
你好，在configuration.yaml中启用该集成并重启ha服务后，原有会话可以继续操作，但无法（在其他浏览器/隐身窗口）中重新登录任何账户、无法生成长期令牌。日志如下：

`2021-04-26 14:25:23 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
resp = await self._request_handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in handle_req
resp = await func(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/components/auth/__init__.py", line 256, in post
return await self._async_handle_auth_code(hass, data, request.remote)
File "/usr/src/homeassistant/homeassistant/components/auth/__init__.py", line 317, in _async_handle_auth_code
refresh_token = await hass.auth.async_create_refresh_token(
File "/usr/src/homeassistant/homeassistant/auth/__init__.py", line 423, in async_create_refresh_token
return await self._store.async_create_refresh_token(
TypeError: async_create_refresh_token() takes from 2 to 7 positional arguments but 8 were given`

禁用该集成后并重启ha服务后即恢复正常。

ha是2021.4的版本。

**Comment by fkueyu** [comment]
同样的问题。
版本        core-2021.5.4
前端版本： 20210504.0 - latest
天猫技能那边当然也就是返回了：Oauth token 返回不正确,请检查, 3秒后返回设备列表

**Comment by neckyaan** [comment]
解决方案：安装nginx，配置用nginx作https代理回落hass，hass不用ssl，直接用http。

**Comment by h376891202** [comment]
解决方案2:
```
docker exec -it homeassistant bash
vi /config/custom_components/zhibot/__init__.py
```
代码修改为如下:
```
def init_auth(self, botname):^M
        # TODO: ...TMD............... OAuth .....................................................................^M
        store = self.hass.auth._store^M
        self._async_create_refresh_token = store.async_create_refresh_token^M
        store.async_create_refresh_token = self.async_create_refresh_token^M
^M
    # 修改位置1 添加参数
    async def async_create_refresh_token(^M
        self,^M
        user: models.User,^M
        client_id: Optional[str] = None,^M
        client_name: Optional[str] = None,^M
        client_icon: Optional[str] = None,^M
        token_type: str = models.TOKEN_TYPE_NORMAL,^M
        access_token_expiration: timedelta = ACCESS_TOKEN_EXPIRATION,^M
        credential: models.Credentials = None,
    ) -> models.RefreshToken:^M
        if access_token_expiration == ACCESS_TOKEN_EXPIRATION:^M
            access_token_expiration = timedelta(days=365)^M
        # 修改位置2 传参数
        return await self._async_create_refresh_token(user, client_id, client_name, client_icon, token_type, access_token_expiration, credential)^M
```

**Comment by neckyaan** [comment]
收到，谢谢

**Comment by vincenthsing** [comment]
排查了大半个月，终于找到是这个原因
